VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsPersonActiveSkill"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Public name As String    '名稱
Public Stage As String    '階段
Public Distance As String    '距離
Public card As String    '卡片
Public Effect As String    '效果
Public NameFontSize As Integer    '名稱字體大小
Public cardFontSize As Integer    '卡片字體大小
Public EffectFontSize As Integer    '效果字體大小



